# Generated by Django 5.1.3 on 2025-02-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpages', '0005_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(max_length=200),
        ),
    ]
