# Generated by Django 5.1.3 on 2025-02-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpages', '0006_alter_enrollment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('partnership_type', models.CharField(choices=[('education', 'Education & Training'), ('internships', 'Internships & Mentorship'), ('software_development', 'Software Development'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
